### ISSUE TITLE
Please update the Live Stream Archive playlist on YT

### ISSUE THREAD

**Issue by FazalAAli** [CodingTrain/website-archive#2483]
I usually watch the whole live streams and noticed the playlist hasn't been updated since march

please let me know if I can help doing this :) Thanks

**Comment by KobeLiesenborgs** [comment]
Hi Fazal!
I'll note this issue down!
Sorry for the late reply as we didn't actively use the issues feature for this repo before!

P.S. you should join [our community discord](https://thecodingtrain.com/discord) for questions and remarks you might have in the future!

**Comment by FazalAAli** [comment]
Thank you! I'll join the discord too :)
